# Generated by Django 4.1.13 on 2026-03-07 18:55

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification_Level',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('User_Id', models.CharField(db_index=True, max_length=100)),
                ('Text', models.TextField()),
                ('Level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], max_length=2)),
                ('Confidence', models.FloatField()),
                ('Description', models.TextField()),
                ('Text_Length', models.IntegerField()),
                ('Word_Count', models.IntegerField()),
                ('Probabilities', djongo.models.fields.JSONField(blank=True, null=True)),
                ('Created_At', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'classification_levels',
                'ordering': ['-Created_At'],
            },
        ),
        migrations.AddIndex(
            model_name='classification_level',
            index=models.Index(fields=['User_Id', '-Created_At'], name='classificat_User_Id_250f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='classification_level',
            index=models.Index(fields=['Level'], name='classificat_Level_e2b5f4_idx'),
        ),
    ]
