# Generated by Django 4.1.13 on 2026-03-25 11:36

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Result',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('User_Id', models.CharField(db_index=True, max_length=100)),
                ('Text', models.TextField()),
                ('Corrected', models.TextField()),
                ('Overall_Score', models.FloatField()),
                ('Grammar_Score', models.FloatField()),
                ('Vocab_Score', models.FloatField()),
                ('Punct_Score', models.FloatField()),
                ('Detected_Issues', djongo.models.fields.JSONField(blank=True, null=True)),
                ('Created_At', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'feedback_results',
                'ordering': ['-Created_At'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback_result',
            index=models.Index(fields=['User_Id', '-Created_At'], name='feedback_re_User_Id_8f00a4_idx'),
        ),
    ]
