# Generated by Django 4.1.13 on 2026-04-05 15:43

import Exam.models
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Attempt',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Attempt_Id', models.CharField(db_index=True, default=Exam.models.generate_attempt_id, max_length=36, unique=True)),
                ('User_Id', models.CharField(db_index=True, max_length=100)),
                ('Level', models.CharField(default='A1', max_length=2)),
                ('Duration_Minutes', models.IntegerField(default=45)),
                ('Started_At', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('Expires_At', models.DateTimeField(db_index=True)),
                ('Submitted_At', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('Status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted'), ('EXPIRED', 'Expired')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('Auto_Submitted', models.BooleanField(default=False)),
                ('Questions', djongo.models.fields.JSONField(blank=True, default=list)),
                ('Answers', djongo.models.fields.JSONField(blank=True, default=list)),
                ('Question_Results', djongo.models.fields.JSONField(blank=True, default=list)),
                ('Total_Points', models.FloatField(default=0.0)),
                ('Total_Score', models.FloatField(default=0.0)),
                ('Percentage', models.FloatField(default=0.0)),
                ('Passed', models.BooleanField(default=False)),
                ('Final_Level', models.CharField(default='A1', max_length=2)),
                ('Final_Confidence', models.FloatField(default=0.0)),
                ('Created_At', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_attempts',
                'ordering': ['-Created_At'],
            },
        ),
        migrations.AddIndex(
            model_name='exam_attempt',
            index=models.Index(fields=['User_Id', '-Created_At'], name='exam_attemp_User_Id_80ae31_idx'),
        ),
        migrations.AddIndex(
            model_name='exam_attempt',
            index=models.Index(fields=['User_Id', 'Status'], name='exam_attemp_User_Id_878231_idx'),
        ),
        migrations.AddIndex(
            model_name='exam_attempt',
            index=models.Index(fields=['-Expires_At'], name='exam_attemp_Expires_17b2e6_idx'),
        ),
    ]
