# Generated by Django 4.1.13 on 2026-05-21 16:48

import Document_Ingestion.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Analysis',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Analysis_Id', models.CharField(db_index=True, default=Document_Ingestion.models.generate_analysis_id, max_length=36, unique=True)),
                ('User_Id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('Pdf_Url', models.CharField(blank=True, default='', max_length=1000)),
                ('Pdf_Storage_Path', models.CharField(blank=True, default='', max_length=1000)),
                ('File_Name', models.CharField(blank=True, default='', max_length=255)),
                ('Page_Count', models.IntegerField(default=0)),
                ('Extraction_Tool', models.CharField(blank=True, default='', max_length=100)),
                ('Page_Results', djongo.models.fields.JSONField(blank=True, default=list)),
                ('Raw_Text', models.TextField(blank=True, default='')),
                ('Clean_Text', models.TextField(blank=True, default='')),
                ('Classification_Level', models.CharField(blank=True, default='', max_length=10)),
                ('Classification_Confidence', models.FloatField(default=0.0)),
                ('Classification_Description', models.TextField(blank=True, default='')),
                ('Classification_Probabilities', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('Feedback_Corrected_Text', models.TextField(blank=True, default='')),
                ('Feedback_Overall_Score', models.FloatField(default=0.0)),
                ('Feedback_Grammar_Score', models.FloatField(default=0.0)),
                ('Feedback_Vocab_Score', models.FloatField(default=0.0)),
                ('Feedback_Punct_Score', models.FloatField(default=0.0)),
                ('Feedback_Detected_Issues', djongo.models.fields.JSONField(blank=True, default=list)),
                ('Status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='COMPLETED', max_length=20)),
                ('Error_Message', models.TextField(blank=True, default='')),
                ('Created_At', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_analyses',
                'ordering': ['-Created_At'],
            },
        ),
        migrations.AddIndex(
            model_name='document_analysis',
            index=models.Index(fields=['User_Id', '-Created_At'], name='document_an_User_Id_5f4647_idx'),
        ),
        migrations.AddIndex(
            model_name='document_analysis',
            index=models.Index(fields=['Analysis_Id'], name='document_an_Analysi_b69c7b_idx'),
        ),
    ]
