# Generated by Django 4.1.13 on 2026-06-16 23:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_analysis',
            name='Raw_Text',
        ),
        migrations.AddField(
            model_name='document_analysis',
            name='Feedback_Dominant_Error',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='document_analysis',
            name='Feedback_Error_Trend',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='document_analysis',
            name='Feedback_Errors',
            field=djongo.models.fields.JSONField(blank=True, default=list),
        ),
    ]
