# Generated by Django 4.1.13 on 2026-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Ingestion', '0002_remove_document_analysis_raw_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_analysis',
            name='Feedback_Fluency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document_analysis',
            name='Feedback_Severity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document_analysis',
            name='Feedback_Text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
