# Generated by Django 4.1.13 on 2026-05-01 16:09

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalized_Plan',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('User_Id', models.CharField(db_index=True, max_length=100)),
                ('Mode', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly')], max_length=16)),
                ('Level', models.CharField(max_length=2)),
                ('Focus_Skills', djongo.models.fields.JSONField(blank=True, default=list)),
                ('Plan', djongo.models.fields.JSONField()),
                ('Created_At', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'personalized_plans',
                'ordering': ['-Created_At'],
            },
        ),
        migrations.AddIndex(
            model_name='personalized_plan',
            index=models.Index(fields=['User_Id', '-Created_At'], name='personalize_User_Id_88c629_idx'),
        ),
        migrations.AddIndex(
            model_name='personalized_plan',
            index=models.Index(fields=['Level'], name='personalize_Level_5dd655_idx'),
        ),
    ]
