# Generated by Django 4.1.13 on 2026-05-02 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized_Plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalized_plan',
            name='Completed_At',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalized_plan',
            name='Current_Period_Index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalized_plan',
            name='Ends_At',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalized_plan',
            name='Is_Active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='personalized_plan',
            name='Starts_At',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personalized_plan',
            name='Updated_At',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='personalized_plan',
            index=models.Index(fields=['User_Id', 'Mode', '-Created_At'], name='personalize_User_Id_5b35f6_idx'),
        ),
        migrations.AddIndex(
            model_name='personalized_plan',
            index=models.Index(fields=['Is_Active', 'User_Id', 'Mode'], name='personalize_Is_Acti_415e01_idx'),
        ),
    ]
