# Generated by Django 4.1.13 on 2026-05-02 15:23

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized_Plan', '0002_personalized_plan_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Details',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('User_Id', models.CharField(db_index=True, max_length=100)),
                ('Plan_Id', models.CharField(db_index=True, max_length=100)),
                ('Task_Id', models.CharField(db_index=True, max_length=200)),
                ('Mode', models.CharField(max_length=16)),
                ('Level', models.CharField(max_length=2)),
                ('Period', models.CharField(blank=True, max_length=32)),
                ('Day', models.CharField(blank=True, max_length=16)),
                ('Title', models.CharField(blank=True, max_length=256)),
                ('Type', models.CharField(blank=True, max_length=64)),
                ('Status', models.CharField(choices=[('todo', 'todo'), ('in_progress', 'in_progress'), ('submitted', 'submitted'), ('reviewed', 'reviewed')], default='todo', max_length=16)),
                ('Input_Text', models.TextField(blank=True)),
                ('Corrected_Text', models.TextField(blank=True)),
                ('Detected_Issues', djongo.models.fields.JSONField(blank=True, default=list)),
                ('Scores', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('Materials_Used', djongo.models.fields.JSONField(blank=True, default=list)),
                ('Material_Quality', models.FloatField(default=0)),
                ('Started_At', models.DateTimeField(blank=True, null=True)),
                ('Ends_At', models.DateTimeField(blank=True, null=True)),
                ('Submitted_At', models.DateTimeField(blank=True, null=True)),
                ('Is_Auto_Submitted', models.BooleanField(default=False)),
                ('Created_At', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('Updated_At', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'task_details',
                'ordering': ['-Created_At'],
            },
        ),
        migrations.AddIndex(
            model_name='task_details',
            index=models.Index(fields=['User_Id', '-Created_At'], name='task_detail_User_Id_f330a4_idx'),
        ),
        migrations.AddIndex(
            model_name='task_details',
            index=models.Index(fields=['User_Id', 'Plan_Id'], name='task_detail_User_Id_15c201_idx'),
        ),
        migrations.AddIndex(
            model_name='task_details',
            index=models.Index(fields=['Plan_Id', 'Task_Id'], name='task_detail_Plan_Id_edc38f_idx'),
        ),
    ]
