# Generated by Django 4.1.13 on 2026-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized_Plan', '0004_personalized_plan_source_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_details',
            name='Status',
            field=models.CharField(choices=[('todo', 'todo'), ('in_progress', 'in_progress'), ('submitted', 'submitted'), ('reviewed', 'reviewed'), ('cancelled', 'cancelled')], default='todo', max_length=16),
        ),
    ]
