# Generated by Django 4.1.13 on 2026-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized_Plan', '0005_alter_task_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_details',
            name='Correction_Reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task_details',
            name='Example_Correction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task_details',
            name='Example_Error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task_details',
            name='Explanation',
            field=models.TextField(blank=True),
        ),
    ]
